#!/bin/bash

cd ~/

if [ -d ".config/fastshard/$1" ]; then
  echo "🢒 $1 Theme exists"
  cd ~/.config/fastshard/$1 && cp -r * ~/.config/ && sudo chmod +x ~/.config/* && sudo chmod +x ~/.config/*/* && sudo chmod +x ~/.config/*/*/*
  echo "🢒 $1 Has been set as the current Theme"
else
  echo "🢒 Error: Theme $1 is not Installed"
  echo "🢒 Install the Themes from github.com/FastShard/Themes"
fi
